### PR TITLE
WIP implementation of NewFromFloat32

### PR DESCRIPTION
**Pull request by alexpantyukhin**

### CODE REVIEW

**Comment by mewmew** [comment]
Hi Alexander,

Thanks for starting to work on the binary128 implementation! Let me know if you'd like to continue work on this PR (as you've marked it with WIP).

We can also merge it as is now, and continue with further PR to implement the other missing pieces, add test cases, etc.

Cheers,
Robin

**Comment by alexpantyukhin** [comment]
Hi Robin! yes it would be great tomerge it now

**Comment by mewmew** [comment]
> Hi Robin! yes it would be great tomerge it now

Done. Thanks for the PR Alex!

**Comment by alexpantyukhin** [comment]
you are always welcome!

**Pull request merged**
